import enLocale from 'element-ui/lib/locale/lang/en'
export default {
  languages: [{
    text: 'Chinese',
    val: 'zh'
  }, {
    text: 'English',
    val: 'en'
  }],
  menus: {
    yesterdayData: 'Data Yesterday',
    qdManage: 'Agent Management',
    addQd: 'New Agent',
    merManage: 'Merchant',
    salesmanManage: 'Sales Rep.',
    tradeManage: 'Transactions',
    forms: 'Reports',
    formMerIn: 'New Merchants',
    formTrade: 'Merchant Transactions',
    formChannel: 'Agent Merchant Statistic',
    formCTrade: 'Agent Transactions',
    formSalesman: 'Sales Rep. Statistic',
    formLostMer: 'Merchant Loss',
    settle: 'Payouts',
    merSettle: 'Merchant Payout Bill',
    qdFenrun: 'Agent Profits',
    ad: 'Advertisements',
    aders: 'Advertiser',
    notice: 'Notifications',
    addNotice: 'New Notifications',
    meterial: 'Training',
  },
  app: {
    logout: 'Logout',
    fixPass: 'Change Password',
    myFenrun: 'My Profits',
    backLogin: 'Return',
    backLogin_d: 'Change password success. Please click on Confirm and login again.',
    oldPass: 'Old Password',
    newPass: 'New Password',
    newPass2: 'Confirm',
    oldPass_input: '',
    Pass_error: '6 to 20 characters',
    newPass_input: '',
    newPass2_input: '',
    newPass2_error: '2 passwords does not match',
    noticeD: '公告详情',
    noticeTitle: '公告标题',
    noticeDetail: '公告内容',
    timeout: 'Time Out',
    dataLoading: 'Loading',
    save: 'Save',
    sure: 'Confirm',
    cancle: 'Cancel',
    unitGe:'',
    unitMoneyZh:'',//废弃
    unitMoney:'',//USD-废弃
    search:'Search',
    clickScan:'Details',
    operate:'Operation',
    note:'Notes',
    all:'All',
    return:'Return',
    modify:'Modify',
    unitMoneyBack:'',//USD-废弃
  },
  yanzheng: {
    qdNum: 'Please enter agent number, numbers only',
    qdName: '请输入渠道名称，长度在 1 到 30 个字符',//暂不使用
    merNum: 'Please enter Merchant No., numbers only',
    merName: 'Please enter merchant name. 1 to 20 characters',
    merNameL: 'Please enter merchant name. 1 to 30 characters',
    tel: 'Please enter a correct phone number',
    salesman: 'Please enter Sales Rep. 1 to 20 characters',
    salesmanL: 'Please enter Sales Rep. 1 to 30 characters',
    sonMer: 'Please enter Sub-Merchant No. 1 to 128 characters',
    salesmanSel: 'Select Sales Rep.',
    salesmanNum: 'Please enter Sales Rep. No. 1 to 20 characters',
    salesmanName: 'Please enter Sales Rep. Name. 1 to 30 characters',
    tradeNum: 'Please enter Serial No. 1 to 200 characters',
    orderNum: 'Please enter order no. 1 to 128 characters',
    timeThan: 'End time should be smaller than Start time',
    timeMonth: 'Searching cannot across months',
    authProSel: 'Select Province',
    authCitySel: 'Select City',
    telAll: 'Phone No.',
    email: 'Email',
    idNumber: 'ID No.',
    picture: 'Photo',
    pictureLength: 'Photo size should be less than 10m',
  },
  login: {
    qdSystem: 'QF Pay Agent System',
    userLogin: 'Login',
    login: 'Login',
    yanzhengName: 'Account Phone No./Email',
    yanzhengPass: 'Password between 6 to 20 characters',
  },
  generalPro: {
    dateBank:{
      lastWeek:'Recent Week',
      lastMonth:'Recent Month',
      lastThreeM:'Recent 3 Months', 
    },
    yanzheng:{
      input: 'Please enter',
      length: '',
      to: 'to',  
      string: 'characters',
      chinese: 'Chinese',   
      inputSlect: 'Select ',   
    },
    searchBank:{
      qdNum:'Agent No.：',
      qdName:'Agent Name：',
      qdStatus:'Agent State：', 
      active:'Active', 
      inactive:'Inactive',  
      timeRange:'Time：',
      timeRangeD:'Select Date',
      merNum:'Merchant No.：',
      merName:'Merchant Name：', 
      tel:'Phone No.：',
      salesman:'Sales Rep.：',
      sonMer:'Sub-Merchant No.：', 
      auditStatus:'Audit State：',
      auditStatusD:'Please select Audit Status', 
      salesmanNum:'Sales Rep. No.：',
      salesmanName:'Sales Rep. Name：',
      salesmanStatus:'State：', 
      onJob:'Working',
      dimission:'On-leave', 
      tradeNum:'Serial No.：', 
      orderNum:'Order No.：',
      payStatus:'Payment State：',
      failure:' Failed',
      success:'Success',
      startTime:'Start：', 
      endTime:'Ends：', 
      tradePrice:'Amount：',
      tradeTime:'Time：',
      tradeStyle:'Type：',
      tradeStatus:'State：',
      tradeDes:'Description：',
    },
    bodyBank:{
      qdNum:'Agent No.',
      qdName:'Agent Name',
      qdName2:'Agent Name',
      qdShortName:'Abbreviation',
      qdStatus:'State',
      baseInfo:'Info',
      accountInfo:'Account',
      proInfo:'Add Values',
      regTime:'Reg. Time',
      open:'Enable',
      close:'Disable',
      closeDeactive:'Disable',
      merNum:'Merchant No.',
      merName:'Merchant Name',
      merFee:'Fee Rate',
      ownerNname:'Owner Name',
      tel:'Phone No.',
      tel2:'Phone No.',
      auditStatus:'Audit State',
      failureCause:'Reject Reason',
      merStatus:'Merchant State',
      salesman:'Sales Rep.',
      sonMer:'Sub-Merchant No.',
      active:'Active',
      deactive:'Deactive',
      activeS:'Active', 
      inactiveS:'Inactive', 
      salesmanNum:'Sales Rep. No.',
      salesmanName:'Sales Rep. Name',
      salesmanStatus:'State', 
      tradeNum:'Serial No.', 
      orderNum:'Order No.',
      tradePrice:'Amount/',
      tradeTime:'Time',
      tradeStyle:'Type',
      tradeStatus:'State',
      tradeD:'Details',
      owner: 'Onwer', 
      telphone: 'Phone No.', 
      lastTradeTime: 'Last Transaction', 
      proNo:'Product No.',
      proName: 'Product Name', 
      proDes: 'Product Introduction', 
      proSel: 'Select Add Value Product', 
      getMoneyName: 'Payee’s Name', 
      bankAccount:' Bank Account',
      headBank: 'Bank Name', 
      headBankSel: 'Select Bank', 
      bankName: 'Branch', 
      settleStyle:'Payout Type',
      settleMothod: 'Payout Method', 
      startMoney: 'Min Payout Amount', 
      wechartFee: 'Wechat Fee Rate', 
      zfbFee:'Alipay Fee Rate',
      qqFee: 'QQ钱包成本费率', 
      jdFee: '京东钱包成本费率', 
      cardFee: '刷卡成本费率', 
      defaultFee: 'Default Fee Rate', 
      qdType: 'Agent Type', 
      ownerId: ' Agent ID', 
      country: 'Country', 
      timeZone:'Time Zone',
      currency: 'Currency', 
      regEmail: 'Email', 
      authProvince: 'Province', 
      authCity: 'City', 
      salesmanTel: 'Sales Rep. Phone No.',
      province: 'Province', 
      city: 'City', 
      businessMan: 'Business Contact', 
      businessEmail:'Business Email',
      financialMan: 'Finance Contact', 
      financialEmail: 'Finance Email', 
      qdManager: 'Agent Manager', 
      qdManagerTel: 'Manager Phone No.', 
      serverManager: 'Service Manger',
      serverManagerTel: 'Manager Phone No.', 
      companyLogo: 'Company LOGO',
      companyIcon: 'Company ICON',
      businessLicense: 'Business License',
      openAccounts: '开户许可证',
      uploadFile: 'Upload',
      qdAddr: 'Agent Address', 
      familyName: 'Name',
      qdManagerName: 'Agent Manager Name', 
      serverManagerName: 'Service Manager Name', 
    },
  },
  home: {
    titleBank: {
      title: 'Data Yesterday'
    },
    dataBank:{
      tradeData:'Amount',
      newNum:'New Merchants',
      income:'Net Income',
    },
    lineBank:{
      tradeLine:'Realtime Transactions',
      merchantLine:'New Merchants',
      trade_x:'Min/HH:MM',
      trade_y:'Amount/',
      trade_d:'Amount Statistic',
      merchant_x:'In a Week/MM',
      merchant_y:'Merchants/Date',
      merchant_d:'Merchants',
    },
  },
  channelList: {
    titleBank: {
      title: 'Agent Info'
    },
    searchBank:{
      download:'Download',         
    },
    bodyBank:{
      tipS:'Are you sure you want to',
      tipE:'the agent',  
      proSuccess:'Success!',  
      fixSuccess:'Success!',           
    },
  },
  merchantlList: {
    titleBank: {
      title: 'Merchant Info'
    },
    searchBank:{  
      download:'Download',         
    },
    bodyBank:{
      feeDetail:'Fee Rate Details',
      feeWeixin:'Wechat',
      feeBao:'Alipay',
      feeJd:'京东费率',
      feeQQ:'QQ钱包费率',
      feeCard:'刷卡费率',
      settleCycle:'Payout Cycle',   
      tipS:'Are you sure you want to',
      tipE:'the merchant',          
    },
  },
  salesmanlList: {
    titleBank: {
      title: 'Sales Rep. Info'
    },
    searchBank:{  
      download:'Download',         
    },
    bodyBank:{
      businessStatistics:'Statistic',  
      month:'Month', 
      merchantNum:'Merchants', 
      auditSucess:'Pass', 
      auditError:'Failed ', 
      auditReject:'Rejected ',  
      tradeMoney:'Amount ', 
      inactive:'Disable', 
      removal:'Merchant Immigrate to',   
      total:'Total',   
      unitGe: '',   
    },
  },
  tradelList: {
    titleBank: {
      title: 'Transactions'
    },
    searchBank:{  
      download:'Download',         
    },
    bodyBank:{   
    },
  },
  tradelDetail: {
    titleBank: {
      title: 'Details'
    },
  },
  formMerchantin: {
    titleBank: {
      title: 'New Merchant Statistic'
    },
    bodyBank:{ 
      selTime: 'Start (Ends in One Week)', 
      timePlace: 'Select Date', 
      lastWeek: 'Recent Week/MM', 
      merInNum: 'New Merchants',  
    },
  },
  formMer: {
    titleBank: {
      title: 'Merchant Transactions'
    },
    bodyBank:{ 
      lineD: 'Amount', 
      lineY: 'Amount/', 
      lineX: 'Time/hr',  
    },
  },
  chanelIn: {
    titleBank: {
      title: 'New Merchant Statistic'
    },
    bodyBank:{ 
      selTime: 'Start (Ends in One Week)', 
      timePlace: 'Select Date',
      lineY: 'New Merchants', 
      lineX: 'Recent One Week/Day', 
      desDate: 'Date', 
      desChannel: 'Sub-Agent on board New Merchants', 
      desChannelNum: 'Sub-Agents', 
      unitPerson: '', 
      unitGe: '',
    },
  },
  forChanelTrade: {
    titleBank: {
      title: 'Agent Statistic'
    },
    bodyBank:{ 
      lineY: 'Amount/', 
      lineX: 'Time/hr', 
      desDate: 'Date', 
      desChannel: ' Sub-Agent transaction amount', 
      desChannelNum: 'Sub-Agents', 
      unitGe: '',
    },
  },
  forSalesman: {
    titleBank: {
      title: 'Sales Rep. Statistic'
    },
    bodyBank:{ 
      lineY: 'New Merchant/Person', 
      lineX: 'Time/Day', 
      desDate: 'Date', 
      desChannel: 'Sales Rep. on board New Merchant', 
      desChannelNum: 'Sales Rep. No', 
      unitPerson: '', 
      unitGe: '',
    },
  },
  forLost: {
    titleBank: {
      title: 'Merchant Loss Statistic'
    },
    bodyBank:{ 
      
    },
  },
  ...enLocale
}
